
var grupo1 = [
  //verbos grupo 1 pag 14

  { english: "Attack", spanish: "Atacar", meanings: ["Atacar", "Ataque"] },
  { english: "Bite", spanish: "Morder", meanings: ["Mordida", "Morder"] },
  { english: "Benefit", spanish: "Beneficiar", meanings: ["Beneficiar", "Beneficio"] },
  { english: "Borrow from", spanish: "Pedir prestado a", meanings: ["Pedir prestado a"] },
  { english: "Lend", spanish: "Dar prestado", meanings: ["Dar prestado"] },
  { english: "Behave", spanish: "Comportarse", meanings: ["Comportarse"] },
  { english: "MisBehave", spanish: "Comportarse mal", meanings: ["Comportarse mal"] },
  { english: "Beat", spanish: "Golpear", meanings: ["Golpear", "Vencer", "Batir", "Latido"] },
  { english: "Come to", spanish: "Venir a", meanings: ["Venir a"] },
  { english: "Go to", spanish: "ir a", meanings: ["Ir a"] },
  { english: "Go on", spanish: "Seguir", meanings: ["Seguir", "Continuar"] },
  { english: "Go away", spanish: "Alejarse", meanings: ["Alejarse", "Irse lejos"] },
  { english: "Enroll", spanish: "Matricular ", meanings: ["Matricular", "Matricularse", "Enrolar", "Inscribirse"] },
  { english: "Eat", spanish: "Comer", meanings: ["Comer"] },
  { english: "Kiss", spanish: "Besar", meanings: ["Besar", "Beso"] },
  { english: "Leave", spanish: "Salir ", meanings: ["Salir", "Abandonar"] },
  { english: "Obey", spanish: "Obedecer", meanings: ["Obedecer"] },
  { english: "Flunk", spanish: "Perder un examen", meanings: ["Perder un examen"] },
  { english: "pass by", spanish: "Pasar por", meanings: ["Pasar por", "Aprobar un examen"] },
  { english: "Pass away", spanish: "Fallecer ", meanings: ["Fallecer", "Morir"] },
  { english: "Shout at", spanish: "Gritar a", meanings: ["Gritar a"] },

]

var grupo2 = [
  //preposiciones pag 16

  { english: "AT", spanish: "En", meanings: ["En"] },
  { english: "IN", spanish: "En dentro", meanings: ["En", "Dentro de"] },
  { english: "OUT", spanish: "Fuera", meanings: ["Fuera"] },
  { english: "FROM", spanish: "De", meanings: ["De", "(indica punto de origen)"] },
  { english: "TO", spanish: "A", meanings: ["A", "(indica hacia donde va el desplazamiento)"] },
  { english: "INSTEAD OF", spanish: "En lugar de", meanings: ["En Lugar de", "por", "en vez de", "en remplazo de"] },
  { english: "BECAUSE OF", spanish: "A causa de", meanings: ["A causa de", "por culpa de", "gracias a"] },
  { english: "FOR", spanish: "Para", meanings: ["Para", "(indica beneficiario)"] },
  { english: "WITH", spanish: "Con", meanings: ["Con", "(indica compañia)"] },
  { english: "WITHOUT", spanish: "Sin", meanings: ["Sin"] },
  { english: "BY", spanish: "Por", meanings: ["por", "(indica quien hace algo)"] },
]
var grupo3 = [
  //verbos grupo 2 pag 17
  { english: "buy", spanish: "Comprar", meanings: ["comprar"] },
  { english: "Sell", spanish: "Vender", meanings: ["vender"] },
  { english: "Catch", spanish: "Capturar", meanings: ["Capturar", "coger"] },
  { english: "Captch up", spanish: "Ponerse al dia", meanings: ["ponerse al dia", "alcanzar"] },
  { english: "Defrost", spanish: "Descongelar", meanings: ["descongelar"] },
  { english: "Freeze", spanish: "Congelar", meanings: ["congelar"] },
  { english: "Give Away", spanish: "Dar ", meanings: ["dar", "Regalar"] },
  { english: "Give up", spanish: "Rendirse", meanings: ["rendirse", "darse por vencido"] },
  { english: "Lose", spanish: "Perder", meanings: ["perder"] },
  { english: "Look at", spanish: "Mirar a", meanings: ["mirar a"] },
  { english: "Look back", spanish: "Voltear a mirar", meanings: ["voltear a mirar", "mirar atras"] },
  { english: "Look for", spanish: "Buscar", meanings: ["buscar"] },
  { english: "Look like", spanish: "Parecerse a", meanings: ["parecerse a"] },
  { english: "Put", spanish: "Poner", meanings: ["poner", "colocar"] },
  { english: "Report", spanish: "Reportar", meanings: ["reportar", "reporte"] },
  { english: "Ride", spanish: "Montar", meanings: ["montar", "(sobre)", "dar un paseo"] },
  { english: "Run for", spanish: "Correr", meanings: ["correr", "presentarse para", "postularse"] }, 
  { english: "Sing", spanish: "Cantar", meanings: ["cantar"] },
  { english: "Study", spanish: "Estudiar", meanings: ["estudiar"] },
  { english: "Walk", spanish: "Caminar", meanings: ["caminar", "caminata"] },
  { english: "Walk away", spanish: "Alejarse", meanings: ["alejarse", "(caminando)"] },
  { english: "Work", spanish: "Trabajar", meanings: ["trabajar", "trabajo"] },

]


var grupo4 = [
  //Verb grupo 3 pag 20
  { english: "Brush", spanish: "Cepillar", meanings: ["cepillar", "cepillo"] },
  { english: "Celebrate", spanish: "Celebrar", meanings: ["celebrar"] },
  { english: "Decide", spanish: "Decidir", meanings: ["decidir"] },
  { english: "Destroy", spanish: "Destrozar", meanings: ["destrozar"] },
  { english: "Dress", spanish: "Vestir", meanings: ["vestir", "vestido", "(de mujer)"] },
  { english: "Give in advance", spanish: "Dar por adelantado", meanings: ["dar por adelantado"] },
  { english: "Mop", spanish: "Trapear", meanings: ["trapear", "trapeador"] },
  { english: "Sweep", spanish: "Barrer", meanings: ["barrer"] },
  { english: "Recommend", spanish: "Recomendar", meanings: ["recomendar"] },
  { english: "Receive", spanish: "Recibir", meanings: ["recibir"] },
  { english: "Travel", spanish: "Viajar", meanings: ["viajar"] },
  { english: "Keep", spanish: "Guardar", meanings: ["guardar", "mantener"] },
  { english: "Answer to", spanish: "responder", meanings: ["responder", "contestar", "(a)", "respuesta"] },
  { english: "Demand", spanish: "Demandar", meanings: ["demandar", "exigir"] },
  { english: "Stand up", spanish: "Ponerse de pie", meanings: ["ponerse de pie", "pararse"] },
  { english: "Sit down", spanish: "Sentarse", meanings: ["sentarse"] },
]
  var grupo5 = [

  //Adverbios de tiempo asociados al imperativo y al presente pag 21
  { english: "Early", spanish: "Temprano", meanings: ["temprano"] },
  { english: "Earlier", spanish: "Mas temprano", meanings: ["mas temprano"] },
  { english: "late", spanish: "Tarde", meanings: ["tarde"] },
  { english: "later", spanish: "Mas Tarde", meanings: ["mas tarde"] },
  { english: "Tonight", spanish: "Esta noche", meanings: ["esta noche"] },
  { english: "Now", spanish: "Ahora", meanings: ["ahora"] },
  { english: "Today", spanish: "Hoy", meanings: ["hoy"] },
  { english: "Tomorrow", spanish: "Mañana", meanings: ["mañana"] },
  { english: "Right now", spanish: "Ya mismo", meanings: ["ya mismo", "enseguida"] },
  { english: "Right Away", spanish: "Ya mismo ", meanings: ["ya mismo", "enseguida"] },
  { english: "At once", spanish: "Ya mismo ", meanings: ["ya mismo", "enseguida"] },
  ]

  var grupo6 = [
  
  //verbos grupo 4 pag 22
  { english: "Apologize", spanish: "Presentar excusas", meanings: ["presentar excusas"] },
  { english: "Apologize to", spanish: "Presentar excusas a", meanings: ["presentar excusas a"] },
  { english: "Agree", spanish: "Estar de acuerdo", meanings: ["Estar de acuerdo"] },
  { english: "Agree with", spanish: "Estar de acuerdo con", meanings: ["Estar de acuerdo con"] },
  { english: "Disagree", spanish: "No estar de acuerdo", meanings: ["no estar de acuerdo"] },
  { english: "Disagree with", spanish: "No estar de acuerdo con", meanings: ["no estar de acuerdo con"] },
  { english: "Arrive", spanish: "Llegar", meanings: ["llegar"] },
  { english: "Arrive to", spanish: "Llegar a", meanings: ["llegar a"] },
  { english: "Address", spanish: "Dirigir ", meanings: ["dirigir", "direccion"] },
  { english: "Admit", spanish: "Admitir", meanings: ["admitir"] },
  { english: "Accept", spanish: "Aceptar", meanings: ["aceptar"] },
  { english: "Believe", spanish: "Creer", meanings: ["creer"] },
  { english: "Bother", spanish: "Molestar", meanings: ["molestar"] },
  { english: "Broadcast", spanish: "Transmitir", meanings: ["transmitir", "(por radio, TV)"] },
  { english: "Name", spanish: "Nombre", meanings: ["nombre", "llamar", "nombrar"] },
  { english: "Discuss", spanish: "Discutir", meanings: ["discutir"] },
  { english: "Fix", spanish: "Arreglar", meanings: ["arreglar", "desquitarse con"] },
  { english: "Help", spanish: "Ayudar", meanings: ["ayudar", "ayuda"] },
  { english: "Miss", spanish: "Extrañar", meanings: ["extrañar", "echar de menos", "señorita", "perder"] },
  { english: "Hold", spanish: "Agarrar", meanings: ["agarrar", "sostener", "abrazar"] },
  { english: "Hold on", spanish: "Resistir", meanings: ["resistir", "esperar", "asirse a"] },
  { english: "Hold the line", spanish: "Sostener la linea", meanings: ["sostener la linea", "(no colgar el telefono)"] },
  { english: "Satisfy", spanish: "Satisfacer", meanings: ["satisfacer"] },
  { english: "Meet", spanish: "Encontrar", meanings: ["encontrar", "conocer"] },
  { english: "Remember", spanish: "Recordar", meanings: ["recordar", "acordarse de", "tener presente"] },

  ]
  var grupo7 = [
  //Vocabulario 1 pagina 23
  { english: "Dad", spanish: "Papa", meanings: ["papa", "(forma hablada)"] },
  { english: "Daddy", spanish: "Papa", meanings: ["papa", "(forma hablada)"] },
  { english: "Mum", spanish: "Mama", meanings: ["mama", "(forma hablada)"] },
  { english: "Parents", spanish: "Padres", meanings: ["padres"] },
  { english: "Family", spanish: "Familia", meanings: ["familia"] },
  { english: "Wife", spanish: "Esposa", meanings: ["esposa"] },
  { english: "wives", spanish: "Esposas", meanings: ["esposas"] },
  { english: "Housewife", spanish: "Ama de casa", meanings: ["ama de casa"] },
  { english: "Husband", spanish: "Esposo", meanings: ["esposo"] },
  { english: "Son", spanish: "Hijo", meanings: ["hijo"] },
  { english: "Daughter", spanish: "Hija", meanings: ["hija"] },
  { english: "Cousin", spanish: "Primo", meanings: ["primo", "prima"] },
  { english: "Nephew", spanish: "Sobrino", meanings: ["sobrino"] },
  { english: "Niece", spanish: "Sobrina", meanings: ["sobrina"] },
  { english: "Uncle", spanish: "Tio", meanings: ["tio"] },
  { english: "Aunt", spanish: "Tia", meanings: ["tia"] },
  { english: "Grandpa", spanish: "Abuelo", meanings: ["abuelo", "(forma hablada)"] },
  { english: "Grandma", spanish: "Abuela", meanings: ["abuela", "(forma hablada)"] },
  { english: "Boy", spanish: "Muchacho", meanings: ["muchacho"] },
  { english: "Girl", spanish: "Muchacha", meanings: ["muchacha"] },
  { english: "Woman", spanish: "Mujer", meanings: ["mujer"] },
  { english: "Women", spanish: "Mujeres", meanings: ["mujeres"] },
  { english: "Man", spanish: "Hombre", meanings: ["hombre"] },
  { english: "Men", spanish: "Hombres", meanings: ["hombres"] },
  { english: "Maid", spanish: "Empleada", meanings: ["empleada", "(del servicio)"] },
  { english: "Brother", spanish: "Hermano", meanings: ["hermano"] },
  { english: "Sister", spanish: "Hermana", meanings: ["hermana"] },
  { english: "Brother in law", spanish: "Cuñado", meanings: ["cuñado"] },
  { english: "Sister in law", spanish: "Cuñada", meanings: ["cuñada"] },
  { english: "Father", spanish: "Papa", meanings: ["papá"] },
  { english: "Mother", spanish: "Mama", meanings: ["mamá"] },
  { english: "Mother in law", spanish: "Suegra", meanings: ["suegra"] },
  { english: "Father in law", spanish: "Suegro", meanings: ["suegro"] },
  { english: "Son in law", spanish: "Yerno", meanings: ["yerno"] },
  { english: "Daughter in law", spanish: "Nuera", meanings: ["nuera"] },
  { english: "Step father", spanish: "Padrastro", meanings: ["padrastro"] },
  { english: "Step mother", spanish: "Madrastra", meanings: ["madrastra"] },
  { english: "Step daunghter", spanish: "Hijastra", meanings: ["hijastra"] },
  { english: "Step son", spanish: "Hijastro", meanings: ["hijastro", ""] },
  { english: "Step brother", spanish: "Hermanastro", meanings: ["hermanastro", ""] },
  { english: "Step sister", spanish: "Hermanastra", meanings: ["hermanastra"] },
  ]

  var grupo8 = [
  //Adjetivos posesivos pag 25  
  { english: "My", spanish: "Mi", meanings: ["Mi", "mis"] },
  { english: "Your", spanish: "Tu", meanings: ["tu", "tus", "su", "sus", "(de usted,de ustedes)"] },
  { english: "Our", spanish: "Nuestro", meanings: ["nuestro", "nuestra", "nuestros", "nuestras"] },
  { english: "Their", spanish: "su", meanings: ["su", "sus", "de ellos", "(de ellas)"] },
  { english: "Her", spanish: "Su", meanings: ["su", "sus", "(de ella)"] },
  { english: "His", spanish: "Su Sus de el", meanings: ["su", "sus", "(de el)"] },
  { english: "Its", spanish: "Su sus de este", meanings: ["su", "sus", "de este, de eso"] },
  ]

  var grupo8 = [ 
  //Verbos grupo 5 pag 26
  { english: "Box", spanish: "Boxear", meanings: ["boxear", "caja"] },
  { english: "Burn", spanish: "Quemar", meanings: ["quemar"] },
  { english: "Burn up", spanish: "Quemarse por completo", meanings: ["quemarse por completo"] },
  { english: "Comb", spanish: "Peinar", meanings: ["peinar", "peineta", "peinarse"] },
  { english: "Cook", spanish: "Cocinar", meanings: ["cocinar", "cocinero"] },
  { english: "Drink", spanish: "Beber", meanings: ["beber", "bebida", "tomar"] },
  { english: "Fight", spanish: "Pelear", meanings: ["pelear", "pelea"] },
  { english: "Hunt", spanish: "Cazar", meanings: ["cazar", "caza"] },
  { english: "Hurry", spanish: "Apresurarse", meanings: ["apresurarse"] },
  { english: "Hurry to", spanish: "Apresurase a", meanings: ["apresuraese a"] },
  { english: "Join", spanish: "Juntar", meanings: ["juntar", "juntarse"] },
  { english: "Learn", spanish: "Aprender", meanings: ["aprender"] },
  { english: "Return", spanish: "Regresar", meanings: ["regresar"] },
  { english: "Teach", spanish: "Enseñar", meanings: ["enseñar"] },
  { english: "Practice", spanish: "Practicar", meanings: ["practicar", "practica"] },
  { english: "Visit", spanish: "Visitar", meanings: ["visitar", "visita"] },
  { english: "Release", spanish: "Liberar", meanings: ["liberar", "(un rehen, un prisionero)", "liberacion"] },
  { english: "Require", spanish: "Requerir", meanings: ["requerir", "necesitar"] },
  { english: "Survive", spanish: "Sobrevivir", meanings: ["sobrevivir"] },
  { english: "Heat", spanish: "Calentarse", meanings: ["calentar", "calentarse", "calor"] },
  { english: "Cool down", spanish: "Enfriar", meanings: ["enfriar", "enfriarse", "calmarse"] },
  ]
  var grupo9 = [
  // Vocabulario 2 pag 26

  { english: "Animal", spanish: "Animal", meanings: ["animal"] },
  { english: "Bear", spanish: "Oso", meanings: ["oso"] },
  { english: "Bull", spanish: "Toro", meanings: ["toro"] },
  { english: "Cage", spanish: "Jaula", meanings: ["jaula", "enjaular"] },
  { english: "Cow", spanish: "Vaca", meanings: ["vaca"] },
  { english: "Cat", spanish: "Gato", meanings: ["gato"] },
  { english: "Dog", spanish: "Perro", meanings: ["perro"] },
  { english: "Bird", spanish: "Pajaro", meanings: ["pajaro"] },
  { english: "Donkey", spanish: "Burro", meanings: ["burro"] },
  { english: "Eagle", spanish: "Aguila", meanings: ["aguila"] },
  { english: "Elephant", spanish: "Elefante", meanings: ["elefante"] },
  { english: "Hawk", spanish: "Halcon", meanings: ["halcon"] },
  { english: "Horse", spanish: "Caballo", meanings: ["caballo"] },
  { english: "Lion", spanish: "Leon", meanings: ["leon"] },
  { english: "Mouse", spanish: "Raton", meanings: ["raton"] },
  { english: "mice", spanish: "Ratones", meanings: ["ratones"] },
  { english: "Meat", spanish: "Carne", meanings: ["carne"] },
  { english: "Monkey", spanish: "Mico", meanings: ["mico"] },
  { english: "Parrot", spanish: "Loro", meanings: ["loro"] },
  { english: "Panther", spanish: "Pantera", meanings: ["pantera"] },
  { english: "Rhino", spanish: "Rinoceronte", meanings: ["rinoceronte"] },
  { english: "Zoo", spanish: "Zoologico", meanings: ["zoologico"] },
  { english: "Tamer", spanish: "Domador", meanings: ["domador"] },
  { english: "Rat", spanish: "Rata", meanings: ["rata"] },
  ]
  var grupo10 = [
  //Verbos grupo 6 pag 28
  { english: "Appreciate", spanish: "Apreciar", meanings: ["apreciar"] },
  { english: "Fish", spanish: "Pescar", meanings: ["pescar", "pescado"] },
  { english: "Fire", spanish: "fuego", meanings: ["echar del trabajo", "incendiar", "fuego", "incendio"] },
  { english: "Fly", spanish: "Volar", meanings: ["volar", "mosca"] },
  { english: "Hire", spanish: "Emplear", meanings: ["emplear", "contratar"] },
  { english: "Inform", spanish: "Informar", meanings: ["informar"] },
  { english: "Improve", spanish: "Mejorar", meanings: ["mejorar"] },
  { english: "Introduce", spanish: "Presentar", meanings: ["presentar", "introducir"] },
  { english: "Invent", spanish: "Inventar", meanings: ["inventar"] },
  { english: "Itch", spanish: "Picar", meanings: ["picar", "picazon"] },
  { english: "Interrupt", spanish: "Interrumpir", meanings: ["interrumpir"] },
  { english: "Joke", spanish: "Bromear", meanings: ["bromear", "broma"] },
  { english: "Line", spanish: "Alinear ", meanings: ["alinear", "linea"] },
  { english: "Mix", spanish: "Mezclar", meanings: ["mezclar", "mezcla"] },
  { english: "Offer", spanish: "Ofrecer ", meanings: ["ofrecer", "oferta"] },
  { english: "Park", spanish: "Parquear ", meanings: ["parquear", "parque"] },
  { english: "Play", spanish: "Jugar ", meanings: ["jugar", "juego", "tocar un instrumento"] },
  { english: "Talk", spanish: "Hablar", meanings: ["hablar", "charlar"] },
  { english: "Talk to", spanish: "Hablar con", meanings: ["hablar con", "charlar com"] },
  { english: "Regret", spanish: "Arrepentirse", meanings: ["arrepentirse", "sentir pena"] },
  { english: "Expect", spanish: "Esperar", meanings: ["esperar", "esperar un hijo"] },
  { english: "Try", spanish: "Tratar", meanings: ["tratar", "intentar"] },
  { english: "Want", spanish: "Querer", meanings: ["querer", "desear"] },
  { english: "Wish", spanish: "Desear ", meanings: ["desear", "(fuertemente)", "deseo"] },
  { english: "Like", spanish: "Gustar, como, Semejante", meanings: ["gustar", "como", "semejante"] },
  ]
  var grupo11 = [
  //Verbos grupo 7 pag 30
  { english: "Dream", spanish: "Soñar ", meanings: ["soñar", "sueño"] },
  { english: "Dream To", spanish: "Soñar con", meanings: ["soñar con", "sueño con"] },
  { english: "Dream about", spanish: "Soñar con", meanings: ["soñar con", "sueño con"] },
  { english: "Go to bed", spanish: "Acostarse", meanings: ["acostarse"] },
  { english: "Plan", spanish: "Planear", meanings: ["planear", "plan"] },
  { english: "read", spanish: "Leer", meanings: ["leer"] },
  { english: "Sleep", spanish: "Dormir", meanings: ["dormir"] },
  { english: "Stop", spanish: "Parar", meanings: ["parar", "parada"] },
  { english: "Stay", spanish: "Quedarse", meanings: ["quedarse", "permanencia"] },
  { english: "Stay alive", spanish: "Sobrevivir", meanings: ["sobrevivir"] },
  { english: "Swim", spanish: "Nadar", meanings: ["nadar"] },
  { english: "Thank", spanish: "Agradecer", meanings: ["agradecer", "gracias"] },
  { english: "Start", spanish: "Empezar", meanings: ["empezar", "arranque"] },
  { english: "Wash", spanish: "Lavar", meanings: ["lavar"] },
  { english: "Watch", spanish: "Mirar", meanings: ["mirar", "reloj de pulso"] },
  { english: "Wake up", spanish: "Despertar", meanings: ["despertar"] },
  { english: "Need", spanish: "Necesitar", meanings: ["necesitar"] },
  { english: "Hope", spanish: "Esperar", meanings: ["esperar", "esperanza"] },
  { english: "Wait", spanish: "Esperar", meanings: ["esperar", "(fisicamente)"] },
  { english: "Wait for", spanish: "Esperar a", meanings: ["esperar a", "(fisicamente)"] },
  { english: "Have", spanish: "Tener", meanings: ["tener"] },
  { english: "Have to", spanish: "Tener que", meanings: ["tener que"] },
  ]
  var grupo12 = [
  //Vocabulario 3 pag 30
  { english: "All", spanish: "Todo", meanings: ["todo", "(adjetivo)"] },
  { english: "Bank", spanish: "Banco", meanings: ["banco"] },
  { english: "Banker", spanish: "Banquero", meanings: ["banquero"] },
  { english: "Blood", spanish: "Sangre", meanings: ["sangre"] },
  { english: "Building", spanish: "Edificio", meanings: ["edificio"] },
  { english: "Bed", spanish: "Cama", meanings: ["cama"] },
  { english: "Cop", spanish: "Policia", meanings: ["policia"] },
  { english: "City", spanish: "Ciudad", meanings: ["ciudad"] },
  { english: "Down town", spanish: "Centro de la ciudad", meanings: ["centro de la ciudad"] },
  { english: "Here", spanish: "Aqui", meanings: ["aqui"] },
  { english: "Town", spanish: "Pueblo", meanings: ["pueblo"] },
  { english: "Police officer", spanish: "Policia", meanings: ["policia"] },
  { english: "This", spanish: "Este", meanings: ["este", "(cerca de quien habla)"] },
  { english: "These", spanish: "Estas", meanings: ["estas", "(cerca de quien habla)"] },
  { english: "That", spanish: "Ese", meanings: ["ese", "(lejos de quien habla)"] },
  { english: "Those", spanish: "Esos", meanings: ["esos", "(lejos de quien habla)"] },
  { english: "There", spanish: "Alli", meanings: ["alli"] },
  { english: "Over there", spanish: "Alla", meanings: ["alla"] },
  { english: "Test", spanish: "Examen", meanings: ["examen"] },
  { english: "Together", spanish: "Juntos", meanings: ["juntos"] },
  { english: "Thief", spanish: "Ladron", meanings: ["ladron"] },
  { english: "Village", spanish: "Pueblito", meanings: ["pueblito", "aldea"] },
  { english: "Popsicle", spanish: "Paleta", meanings: ["paleta"] },
  { english: "Ice cream", spanish: "Helado", meanings: ["helado"] },
  { english: "Candy", spanish: "Caramelo Golosina", meanings: ["caramelo", "golosina"] },
  { english: "Chocolate bar", spanish: " Barra de chocolate", meanings: ["barra de chocolate", "chocolatina"] },
  { english: "Flavor", spanish: "Sabor", meanings: ["sabor"] },
  { english: "Jello", spanish: "Gelatina", meanings: ["gelatina"] },
  { english: "Jelly", spanish: "Jalea", meanings: ["jalea", "gelatina"] },
  { english: "Dairy", spanish: "Lecheria", meanings: ["lecheria"] },
  { english: "Dairy case", spanish: "Seccion de productos lacteos", meanings: ["seccion de productos lacteos"] },
  { english: "Tasty", spanish: "sabroso", meanings: ["sabroso"] },
  ]


//estos quedan pendientes 
  var grupo13 = [
  // 7 verbos 3 caso to, not to

  { english: "Advise", spanish: "Aconsejar", meanings: ["aconsejar"] },
  { english: "Ask", spanish: "Pedir", meanings: ["pedir"] },
  { english: "Insist", spanish: "Insistir", meanings: ["insistir"] },
  { english: "Order", spanish: "Ordenar", meanings: ["ordenar"] },
  { english: "Recomend", spanish: "Recomendar", meanings: ["recomendar"] },
  { english: "Suggest", spanish: "Sugerir", meanings: ["sugerir"] },
  { english: "Tell", spanish: "Decir", meanings: ["decir"] },

  ]

  var grupo14 = [
  //pronombres posesivos pag 32
  { english: "Mine", spanish: "el mio", meanings: ["el mio", "los mios", "las mias", "la mia"] },
  { english: "Yours", spanish: "el suyo", meanings: ["el suyo", "las suyas", "los suyos", "la suya"] },
  { english: "Ours", spanish: "el nuestro", meanings: ["el nuestro", "la nuestra", "las nuestras", "los nuestros"] },
  { english: "Theirs", spanish: "el de ellos", meanings: ["el de ellos", "los de ellos", "la (s) de ellos", "la (s) de ellas"] },
  { english: "His", spanish: "el de el", meanings: ["el de el", "los de el", "la de el", "las de el"] },
  { english: "Hers", spanish: "el de ella", meanings: ["el de ella", "las de ella", "la de ella"] },
  { english: "Its", spanish: "el de este", meanings: ["el de este", "la de este", "los de este", "las de este"] },

  ]
  var grupo15 = [
    //pronombres reflexivos (reflexive pronouns) pag 34
    { english: "Myself", spanish: "yo mismo", meanings: ["yo mismo","a mi mismo"] },
    { english: "Yourself", spanish: "a usted mismo", meanings: ["a usted mismo"] },
    { english: "Yourselves", spanish: "a ustedes mismos", meanings: ["a ustedes mismos"] },
    { english: "Ourselves", spanish: "a nosotros mismos", meanings: ["a nosotros mismos"] },
    { english: "Themselves", spanish: "a ellas mismas", meanings: ["a ellas mismas","a ellos mismos"] },
    { english: "Himself", spanish: "a el mismo", meanings: ["a el mismo"] },
    { english: "Herself", spanish: "a ella misma", meanings: ["a ella misma"] },
    { english: "Itself", spanish: "a este mismo", meanings: ["a este mismo","a esta misma"] },


  ]
  var grupo16 = [
  //Verbs, group eigh 8  pag 39

  { english: "Ache", spanish: "dolor", meanings: ["dolor", "doler"] },
  { english: "Attach", spanish: "pegar", meanings: ["pegar", "adherir"] },
  { english: "Clean", spanish: "limpiar", meanings: ["limpiar", "limpio"] },
  { english: "Consider", spanish: "considerar", meanings: ["considerar", "pensar"] },
  { english: "Close", spanish: "cerrar", meanings: ["cerrar"] },
  { english: "Crack", spanish: "crujir", meanings: ["crujir", "agrietarse", "crujido", "estallido"] },
  { english: "Cramp", spanish: "dar calambre", meanings: ["dar calambre", "calambre"] },
  { english: "Declare", spanish: "declarar", meanings: ["declarar"] },
  { english: "Delete", spanish: "suprimir", meanings: ["suprimir", "eliminar", "borrar", "(en el computador)"] },
  { english: "Desire", spanish: "desear", meanings: ["desear", "deseo"] },
  { english: "End", spanish: "Terminar", meanings: ["terminar", "fin"] },
  { english: "Get nervous", spanish: "ponerse nervioso", meanings: ["ponerse nervioso"] },
  { english: "Get left behind", spanish: "Quedarse atras", meanings: ["quedarse atras"] },
  { english: "Grab", spanish: "agarrar", meanings: ["agarrar"] },
  { english: "Invest", spanish: "invertir", meanings: ["invertir"] },
  { english: "Knell", spanish: "arrodillarse", meanings: ["arrodillarse", "hincarse"] },
  { english: "Loathe", spanish: "detestar", meanings: ["detestar"] },
  { english: "Lock", spanish: "Echar llave", meanings: ["Echar llave", "cerrar", "cerradura", "candado"] },
  { english: "Unlock", spanish: "Abrir la cerradura", meanings: ["abrir la cerradura", "quitar llave"] },
  { english: "Long", spanish: "largo", meanings: ["largo"] },
  { english: "Long (for, to)", spanish: "anhelar", meanings: ["anhelar", "desear"] },
  { english: "Open", spanish: "abrir", meanings: ["abrir"] },


]

var grupo17 = [
  //verbos grupo 9 (Verbs, grou 9) pag 40
  { english: "Allow", spanish: "permitir", meanings: ["permitir"] },
  { english: "Begin", spanish: "empezar", meanings: ["comenzar", "comenzar"] },
  { english: "Cry", spanish: "llorar", meanings: ["llorar"] },
  { english: "Check", spanish: "revisar", meanings: ["cheque", "revisar", "verificar", "cuenta", "(en restaurantes)"] },
  { english: "Disturb", spanish: "perturbar", meanings: ["perturbar", "interrumpir"] },
  { english: "Die", spanish: "morir", meanings: ["morir"] },
  { english: "Live", spanish: "vivir", meanings: ["vivir"] },
  { english: "Let", spanish: "permitir", meanings: ["permitir","dejar"] },
  { english: "Escape", spanish: "escapar", meanings: ["escapar"] },
  { english: "Fail", spanish: "Fracasar", meanings: ["fracasar","fallar"] },
  { english: "Wipe", spanish: "amarrar", meanings: ["amarrar","atar","ataduras","lazos","corbata","empatar"] },
  { english: "Marry", spanish: "casarse ", meanings: ["casarse con"] },
  { english: "Pay", spanish: "pagar", meanings: ["pagar"] },
  { english: "Pay for", spanish: "pagar por", meanings: ["pagar por"] },
  { english: "Succed", spanish: "tener exito", meanings: ["temer exito"] },
  { english: "Fall", spanish: "caer", meanings: ["caer","catarata","otoño"] },
  { english: "Fall down", spanish: "caerse", meanings: ["caerse"] },
  { english: "Fall in love", spanish: "enamorarse", meanings: ["Enamorarse"] },
  { english: "Fall in love with", spanish: "enamorarse de", meanings: ["enamorarse de"] },
  { english: "Turn", spanish: "Girar", meanings: ["girar","voltear","(hacia)", "turno","giro"] },

]

var grupo18 = [
  //Frequency adverbs associate to the presnt tense pag 44
  { english: "Always", spanish: "siempre", meanings: ["siempre"] },
  { english: "Never", spanish: "nunca", meanings: ["nunca"] },
  { english: "Often", spanish: " a menudo", meanings: ["a menudo"] },
  { english: "Only", spanish: "solamente", meanings: ["solamente"] },
  { english: "Rarely", spanish: "raramente", meanings: ["raramente"] },
  { english: "Seldom", spanish: "raramente", meanings: ["raramente"] },
  { english: "Still", spanish: "todavia", meanings: ["todavia", "aun"] },
  { english: "Usually", spanish: "usualmente", meanings: ["usualmente"] },
  { english: "Most days", spanish: "la mayoria de los dias", meanings: ["la mayoria de los dias"] },
  { english: "Twice a week", spanish: "dos veces por semana", meanings: ["dos veces por semana"] },
  { english: "Twice a month", spanish: "dos veces por mes", meanings: ["dos veces por mes"] },
  { english: "Twice a year", spanish: "dos veces por año", meanings: ["dos veces por año"] },
  { english: "In the morning", spanish: "por la mañana", meanings: ["por la mañana"] },
  { english: "In the afternoon", spanish: "por la tarde", meanings: ["por la tarde"] },
  { english: "At noon", spanish: "al medio dia", meanings: ["al medio dia"] },
  { english: "In the evening", spanish: "por la tarde", meanings: ["por la tarde", "(de las 5pm hasta acostarse)"] },
  { english: "At night", spanish: "en la noche", meanings: ["en la noche","(por)"] },
  { english: "At midnight", spanish: "a la media noche", meanings: ["a la media noche"] },
  { english: "On Monday", spanish: "el lunes", meanings: ["el lunes"] },
  { english: "On Tuesday", spanish: "el martes", meanings: ["el martes"] },
  { english: "On Wednesday", spanish: "el miercoles", meanings: ["el miercoles"] },
  { english: "On Thursday", spanish: "el jueves", meanings: ["el jueves"] },
  { english: "On Friday", spanish: "el viernes", meanings: ["el viernes"] },
  { english: "On Saturday", spanish: "el sabado", meanings: ["el sabado"] },
  { english: "On sunday", spanish: "el domingo", meanings: ["el domingo"] },
  { english: "On Sunday morning", spanish: "el domingo por la mañana", meanings: ["el domingo por la mañana"] },
  { english: "On Saturday afternoon", spanish: "el sabado por la tarde", meanings: ["el sabado por la tarde"] },

]

var grupo19 = [
  //verbos grupo 10 pag 43-44

  { english: "Argue", spanish: "discutir", meanings: ["discutir"] },
  { english: "Attend", spanish: "asistir", meanings: ["asistir", "(estar presente en)", "cuidar de"] },
  { english: "Arrest", spanish: "arrestar", meanings: ["arrestar"] },
  { english: "Warm up", spanish: "calentar", meanings: ["calentar","tibio"] },
  { english: "Take away", spanish: "quitar", meanings: ["quitar"] },
  { english: "Take off", spanish: "quitarse", meanings: ["quitarse","despegar", "(un avion)"] },
  { english: "Annoy", spanish: "enojar", meanings: ["enojar"] },
  { english: "Bring", spanish: "traer", meanings: ["traer"] },
  { english: "Cheat", spanish: "hacer trampa", meanings: ["hacer trampa","trampa"] },
  { english: "Take", spanish: "llevar", meanings: ["llevar"] },
  { english: "Flush (the toilet)", spanish: "descargar", meanings: ["descargar","(el inodoro)"] },
  { english: "Hate", spanish: "odiar", meanings: ["odiar"] },
  { english: "Love", spanish: "amar", meanings: ["amar"] },
  { english: "Respect", spanish: "respetar", meanings: ["respetar"] },
  { english: "Rewiew", spanish: "repasar", meanings: ["repasar","repaso"] },
  { english: "Train", spanish: "entrenar", meanings: ["entrenar","(se)","tren"] },
  { english: "Quit", spanish: "retirarse", meanings: ["retirarse","abandonar","dejar de hacer algo"] },
  { english: "Stumble", spanish: "tropezar", meanings: ["tropezar","traspie"] },
  { english: "Light", spanish: "iluminar", meanings: ["iluminar","encender","luz","liviano"] },
  { english: "Value", spanish: "cotizar", meanings: ["cotizar","valor"] },
  { english: "Assess", spanish: "evaluar", meanings: ["evaluar","valorar"] },
  { english: "Trouble", spanish: "preocupar", meanings: ["preocupar","molestar","molestia","dificultad"] },

]

var grupo20 = [  
  
  //expresiones utiles**pag 45-46
  { english: "A lot", spanish: "bastante", meanings: ["bastante","mucho"] },  
  { english: "A lot of", spanish: "bastante de", meanings: ["bastante de", "mucho de"] },
  { english: "A great deal", spanish: "bastante", meanings: ["bastante", "mucho"] },
  { english: "A great deal of", spanish: "bastante de", meanings: ["bastante de", "mucho de"] },
  { english: "All of them", spanish: "todos ellos", meanings: ["todos ellos"] },
  { english: "both of them", spanish: "ambos", meanings: ["ambos"] },
  { english: "from time to time", spanish: "de vez en cuando", meanings: ["de vez en cuando"] },
  { english: "For a while", spanish: "por un rato", meanings: ["por un rato", "por un tiempo"] },
  { english: "As soon as possible", spanish: "tan pronto como sea posible", meanings: ["tan pronto como sea posible"] },
  { english: "Sooner or later", spanish: "tarde o temprano", meanings: ["tarde o temprano"] },
  { english: "A bit", spanish: "un poquito", meanings: ["un poquito"] },
  { english: "A bit of", spanish: "un poquito de", meanings: ["un poquito de"] },
  { english: "Nothing to worry", spanish: "nada de que preocuparse", meanings: ["nada de que procuparse"] },
  { english: "It all seems like yesterday", spanish: "todo parece que fue ayer", meanings: ["todo parece que fue ayer"] },
  { english: "Never mind", spanish: "no se preocupe", meanings: ["no se preocupe"] },
  { english: "You'd better", spanish: "mejor usted ", meanings: ["mejor usted","es mejor que tu"] },
  { english: "It's water down the bridge", spanish: "es cosa del pasado", meanings: ["es cosa del pasado"] },
  { english: "As a watter of facts", spanish: "en efecto", meanings: ["en efecto","en realidad"] },
  { english: "Can't help it", spanish: "no podemos evitarlo", meanings: ["no podemos evitarlo"] },
  { english: "Go to hell!", spanish: "vayyase al infierno", meanings: ["vayase al infierno"] },
  { english: "I think so, too", spanish: "yo tambien creo eso", meanings: ["yo tambien creo eso"] },
  { english: "Just in case", spanish: "por si acaso", meanings: ["por si acaso"] },
  { english: "What happens?", spanish: "que pasa", meanings: ["que pasa","(?)"] },

]

var grupo21 =[
  //verbs, group 11 *** pag 49
  { english: "Contradict", spanish: "contradecir", meanings: ["contradecir"] },
  { english: "Convince", spanish: "convencer", meanings: ["convencer"] },
  { english: "Cross", spanish: "cruzar", meanings: ["cruzar", "traicionar","cruz"] },
  { english: "Criticize", spanish: "criticar", meanings: ["criticar"] },
  { english: "Copy", spanish: "copiar", meanings: ["copiar"] },
  { english: "Copy from", spanish: "copiar a", meanings: ["copiar a "] },
  { english: "Change", spanish: "cambiar", meanings: ["cambiar","cambio"] },
  { english: "Charge", spanish: "cobrar", meanings: ["cobrar","cargar a la cuenta"] },
  { english: "Compare", spanish: "comparar", meanings: ["comparar"] },
  { english: "Create", spanish: "crear", meanings: ["crear"] },
  { english: "Seem", spanish: "Parecer", meanings: ["parecer"] },
  { english: "Seem like", spanish: "parecer como", meanings: ["parecer como"] },
  { english: "Complain", spanish: "quejarse", meanings: ["quejarse"] },
  { english: "Complain about", spanish: "quejarse de", meanings: ["quejarse de"] },
  { english: "Complain for", spanish: "quejarse por", meanings: ["quejarse por"] },
  { english: "Care (about)", spanish: "importarle a uno", meanings: ["importarle a uno","(acerca de)"] },
  { english: "Take care", spanish: "cuidar", meanings: ["cuidar"] },
  { english: "Take care of", spanish: "cuidar de", meanings: ["cuidar de","cuidar a"] },
  { english: "Sail", spanish: "Navegar", meanings: ["navegar","zarpar"] },
  { english: "Set free", spanish: "dejar libre", meanings: ["dejar libre"] },
  { english: "Treat", spanish: "tratar", meanings: ["tratar"] },
  { english: "Invite", spanish: "invitar", meanings: ["invitar"] },
  { english: "Plot", spanish: "conspirar", meanings: ["conspirar","complot"] },
  { english: "Push", spanish: "empujar", meanings: ["empujar","empujon","precionar","(a alguien)"] },
  { english: "preach", spanish: "predicar", meanings: ["predicar"] },
  { english: "Paste", spanish: "pegar", meanings: ["pegar","(en el computador)", "pasta","pate"] },
  { english: "Remove", spanish: "quitar", meanings: ["quitar","trasladar"] },
  { english: "Rest", spanish: "descansar", meanings: ["descansar","descanso","resto"] },
  { english: "Rule", spanish: "gobernar", meanings: ["gobernar","mandar","regla"] },
  { english: "Select", spanish: "seleccionar", meanings: ["seleccionar","selecto","escogido"] },
]
var grupo22 = [
  //Vocabulary four (4)******* pag 49-50
  { english: "Bay", spanish: "bahia", meanings: ["bahia"] },
  { english: "Breeze", spanish: "brisa", meanings: ["brisa"] },
  { english: "Beach", spanish: "playa", meanings: ["playa"] },
  { english: "Boat", spanish: "bote", meanings: ["bote"] },
  { english: "Captain", spanish: "capitan", meanings: ["capitan"] },
  { english: "Continent", spanish: "continente", meanings: ["continente"] },
  { english: "Canoe", spanish: "canoa", meanings: ["canoa"] },
  { english: "Country", spanish: "pais", meanings: ["pais", "campo"] },
  { english: "Gulf", spanish: "golfo", meanings: ["golfo"] },
  { english: "Ocean", spanish: "oceano", meanings: ["oceano"] },
  { english: "Sailor", spanish: "Marinero", meanings: ["marinero"] },
  { english: "Sea", spanish: "Mar", meanings: ["mar"] },
  { english: "Ship", spanish: "Barco", meanings: ["barco", "despachar"] },
  { english: "Shore", spanish: "playa", meanings: ["playa","orilla","costa","litoral"] },
  { english: "Shark", spanish: "tiburon", meanings: ["tiburon"] },
  { english: "Port", spanish: "puerto", meanings: ["puerto"] },
  { english: "Water", spanish: "agua", meanings: ["agua"] },
  { english: "Island", spanish: "isla", meanings: ["isla"] },
  { english: "Moon", spanish: "luna", meanings: ["luna"] },
  { english: "Sun", spanish: "sol", meanings: ["sol"] },
  { english: "Star", spanish: "estrella", meanings: ["estrella"] },
  { english: "Sky", spanish: "cielo", meanings: ["cielo"] },
  { english: "Wind", spanish: "viento", meanings: ["viento"] },
  { english: "Storm", spanish: "tormenta", meanings: ["tormenta"] },
  { english: "Thunder", spanish: "trueno", meanings: ["trueno","tronar"] },
  { english: "Rain", spanish: "lluvia", meanings: ["lluvia","llover"] },
]
var grupo23 = [
  //information questions ***pag 52
  { english: "Why", spanish: "por que", meanings: ["por que","(por que?)"] },
  { english: "what", spanish: "que", meanings: ["que","(que?)"] },
  { english: "What with", spanish: "con quien", meanings: ["con quien","(con quie?)"] },
  { english: "Whom", spanish: "a quien", meanings: ["a quien","(a quien?)"] },
  { english: "Which", spanish: "que", meanings: ["que","cual", "(que, cual?)"] },
  { english: "How", spanish: "como", meanings: ["como","(como?)"] },
  { english: "Where", spanish: "donde", meanings: ["donde","(donde?)"] },
  { english: "When", spanish: "cuando", meanings: ["cuando","(cuando?)"] },
  

]

var grupo24 = [
  //Vocabulary five *********pag 54 -55
  
  { english: "Almighty", spanish: "poderoso", meanings: ["poderoso"] },
  { english: "Book / Textbook", spanish: "libro", meanings: ["libro"] },
  { english: "Backpack", spanish: "mochila", meanings: ["mochila", "maletin"] },
  { english: "Board", spanish: "tablero", meanings: ["tablero"] },
  { english: "Calculator", spanish: "calculadora", meanings: ["calculadora"] },
  { english: "Chair / Seat", spanish: "asiento", meanings: ["asiento","silla"] },
  { english: "Color pencil", spanish: "lapiz de colorear", meanings: ["lapiz de colorear"] },
  { english: "Crooked", spanish: "torcido", meanings: ["torcido","corrupto","deshonesto","encorvado"] },
  { english: "Deal", spanish: "trato", meanings: ["trato","tratar","(con)"] },
  { english: "Desk", spanish: "Escritorio", meanings: ["escritorio"] },
  { english: "Devil", spanish: "demonio", meanings: ["demonio"] },
  { english: "Doctor", spanish: "doctor", meanings: ["doctor"] },
  { english: "Dentist", spanish: "dentista", meanings: ["dentista"] },
  { english: "Nurse", spanish: "Enfermera", meanings: ["enfermera"] },
  { english: "Dust", spanish: "polvo", meanings: ["polvo","desempolvar"] },
  { english: "Eraser", spanish: "borrador", meanings: ["borrador"] },
  { english: "Flag", spanish: "bandera", meanings: ["bandera"] },
  { english: "Garbage", spanish: "basura", meanings: ["basura"] },
  { english: "Garbage can", spanish: "caneca de la basura", meanings: ["caneca de la basura"] },
  { english: "Garbage truck", spanish: "camion de la basura", meanings: ["camion de la basura"] },
  { english: "Bag", spanish: "bolsa", meanings: ["bolsa","cartera","monedero"] },
  { english: "Garbage bag", spanish: "bolsa de la basura", meanings: ["bolsa de la basura"] },
  { english: "Lullaby", spanish: "arrullo", meanings: ["cancion de cuna","arrullo"] },
  { english: "Medicine", spanish: "medicina", meanings: ["medicina"] },
  { english: "Traffic light", spanish: "semaforo", meanings: ["semaforo"] },
  { english: "Crosswalk", spanish: "paso peatonal", meanings: ["paso peatonal"] },

  { english: "God", spanish: "dios", meanings: ["dios"] },
  { english: "Good looking", spanish: "atractivo", meanings: ["atractivo"] },
  { english: "Heaven", spanish: "cielo", meanings: ["cielo"] },
  { english: "Hell", spanish: "infierno", meanings: ["infierno"] },
  { english: "Honey", spanish: "miel de aveja", meanings: ["miel de abeja", "cariñito"] },
  { english: "Ink", spanish: "tinta", meanings: ["tinta"] },
  { english: "Judge", spanish: "juez", meanings: ["juez", "juzgar"] },
  { english: "Jury", spanish: "jurado", meanings: ["jurado"] },
  { english: "Knot", spanish: "nudo", meanings: ["nudo","anudar"] },
  { english: "Law", spanish: "ley", meanings: ["ley"] },
  { english: "Marker", spanish: "marcador", meanings: ["marcador"] },
  { english: "Notebook", spanish: "cuaderno", meanings: ["cuaderno"] },
  { english: "Pen", spanish: "lapicero", meanings: ["lapicero"] },
  { english: "Pencil", spanish: "lapiz", meanings: ["lapiz"] },
  { english: "Powerful", spanish: "poderoso", meanings: ["poderoso"] },
  { english: "People", spanish: "Gente", meanings: ["gente"] },
  { english: "Reward", spanish: "Recompensa", meanings: ["recompensa"] },
  { english: "Road", spanish: "carretera", meanings: ["carretera"] },
  { english: "Ruler", spanish: "regla", meanings: ["regla"] },
  { english: "Sharpener", spanish: "sacapuntas", meanings: ["sacapuntas"] },
  { english: "Trial", spanish: "juicio", meanings: ["juicio","ensayo"] },
  { english: "Treatment", spanish: "trato", meanings: ["trato"] },
  { english: "Tangle", spanish: "enredado", meanings: ["enredado","enrredo","enrredar"] },
  { english: "Terrible", spanish: "terrible", meanings: ["terrible"] },
  { english: "Way", spanish: "ruta", meanings: ["ruta","camino"] },
  { english: "Raise your hand", spanish: "alzar la mano", meanings: ["alzar la mano"] },
  { english: "Work in groups", spanish: "trabajar en grupos", meanings: ["trabajar en grupos"] },
  
  
]

//useful expression pag 56

var grupo25 = [
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
]



//vocabulary six (6) pag 58
var grupo26 = [

   { english: "Boy friend", spanish: "Novio", meanings: ["Novio"] },
   { english: "Girl friend", spanish: "novia", meanings: ["novia"] },
   { english: "Breakfast", spanish: "Desayuno", meanings: ["desayuno"] },
   { english: "Lunch", spanish: "almuerzo", meanings: ["almuerzo"] },
   { english: "Dinner", spanish: "comida", meanings: ["comida", "cena"] },
   { english: "Have breakfast", spanish: "desayunar", meanings: ["desayunar"] },
   { english: "Have lunch", spanish: "almorzar", meanings: ["almorzar"] },
   { english: "Have dinner", spanish: "cenar", meanings: ["cenar"] },
   { english: "Food", spanish: "Alimento", meanings: ["alimento"] },
   { english: "Meal", spanish: "comida", meanings: ["comida"] },
   { english: "Student", spanish: "Estudiante", meanings: ["estudiante"] },
   { english: "Classmate", spanish: "Compañero de clase", meanings: ["compañero de clase"] },
   { english: "Teacher", spanish: "profesor", meanings: ["profesor"] },
   { english: "professor", spanish: "profesor", meanings: ["profesor","(altamente calificado)"] },
   { english: "Primary school", spanish: "escuela primaria", meanings: ["escuela primaria"] },
   { english: "High school", spanish: "colegio", meanings: ["colegio"] },
   { english: "Tuition", spanish: "Matricula", meanings: ["matricula","precio de la enseñanza"] },
   { english: "Schedule", spanish: "horario", meanings: ["horario"] },
   { english: "Break", spanish: "regreo", meanings: ["regreo", "descanso"] },
   { english: "Break time", spanish: "hora de recreo", meanings: ["hora de recreo"] },
   { english: "Exam", spanish: "examen", meanings: ["examen"] },
   { english: "Grade", spanish: "nota", meanings: ["nota", "calificacion", "calificar"] },
   { english: "Monthly payment", spanish: "mensualidad", meanings: ["mensualidad"] },

]



//pronombres indefinidos 5 pag 58
var grupo27 = [
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
]



//verbs, group twelve (12). pag 60
var grupo28 = [
  { english: "Cash", spanish: "cambiar en efectivo", meanings: ["cambiar en efectivo","dinero en efectivo"] },
  { english: "Crash", spanish: "estrellarse", meanings: ["estrellarse","chocar", "choque"] },
  { english: "Call", spanish: "llamar", meanings: ["llamar","llamada"] },
  { english: "Complete", spanish: "completar", meanings: ["completar","completo","(adjetivo)"] },
  { english: "Complicate", spanish: "complicar", meanings: ["complicar","complicado","(adjetivo)"] },
  { english: "Envy", spanish: "envidiar", meanings: ["envidiar"] },
  { english: "Enjoy", spanish: "disfrutar", meanings: ["disfrutar"] },
  { english: "Explain", spanish: "explicar", meanings: ["explicar"] },
  { english: "Fool", spanish: "embobar", meanings: ["embobar","tomar el pelo","bobo","tonto"] },
  { english: "Land", spanish: "Aterrizar", meanings: ["aterrizar","tierra"] },
  { english: "Kick", spanish: "patear", meanings: ["patear","patada"] },
  { english: "Kid", spanish: "Bromear", meanings: ["Bromear","niño"] },
  { english: "Listen", spanish: "escuchar", meanings: ["escuchar"] },
  { english: "Listen to", spanish: "escuchar a", meanings: ["escuchar a"] },
  { english: "Boil", spanish: "Hervir", meanings: ["hervir"] },
  { english: "Bury", spanish: "enterrar", meanings: ["enterrar"] },
  { english: "Crush", spanish: "aplastar", meanings: ["aplastar","triturar"] },
  { english: "Hug", spanish: "abrazar", meanings: ["abrazar","abrazo"] },
  { english: "Realize", spanish: "darse cuenta", meanings: ["darse cuenta","(de)"] },
]

//conectores (Connectives) pagina 62-63
var grupo29 = [
  { english: "And", spanish: "y", meanings: ["y"] },
  { english: "Both...and", spanish: "ambas cosas", meanings: ["ambas cosas"] },
  { english: "Either...or", spanish: "cualquiera de los dos", meanings: ["cualquiera de los dos","uno u otro"] },
  { english: "Neither...nor", spanish: "ni...ni", meanings: ["ni...ni","ninguno de los dos","ni uno ni otro"] },
  { english: "Because", spanish: "porque", meanings: ["porque"] },
  { english: "But", spanish: "pero", meanings: ["pero"] },
  { english: "If...them", spanish: "si...entonces", meanings: ["si...entonces","si entonces","(condicional)"] },
  { english: "Or", spanish: "o", meanings: ["o"] },
  { english: "That", spanish: "que", meanings: ["que"] },
  { english: "then", spanish: "luego", meanings: ["luego","entonces"] },
  { english: "Therefore", spanish: "por consiguiente", meanings: ["por consiguiente","por lo tanto","de esa manera"] },
  { english: "That's because", spanish: "eso es porque", meanings: ["eso es porque"] },
  { english: "That's why", spanish: "por eso es que", meanings: ["por eso es que"] },
  { english: "Because of that", spanish: "a causa de eso", meanings: ["a causa de eso"] },
  { english: "When", spanish: "cuando", meanings: ["cuando"] },
  { english: "Where", spanish: "donde", meanings: ["donde"] },
  { english: "That's what", spanish: "eso es lo que", meanings: ["eso es lo que"] },
  { english: "That's how", spanish: "eso es como", meanings: ["eso es como","esa es la manera como"] },
  { english: "Not only...but (also)", spanish: "no solo...sino", meanings: ["no solo...sino","(tambien)"] },

  /*{ english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  { english: "", spanish: "", meanings: [""] },
  
    */
  
]